@startuml

!define CLR_BG #3C3F41

skinparam {

  shadowing false
    BackgroundColor   CLR_BG
  
    default {
      Border {
        Color Grey
        Thickness 1
      }
      Font {
        Color   DarkGrey
        Name    "Ubuntu Mono"
        Size    8
      }
      Stereotype {
        Border {
          Color CLR_BG
          Thickness 1
        }
      }
    }
  
    title {
      Font {
        Size        30
      }
    }
  
    legend {
      BackgroundColor CLR_BG
      Border {
        Color     CLR_BG
      }
      Font {
        Color       #a0a0a0
        Size        10
      }
    }

  header {
    Font {
      Color DarkGrey
      Size 7
    }
  }
  
  footer {
    Font {
      Color DarkGrey
    }
  }
  
  note {
    BackgroundColor CLR_BG
    Border {
      Color Grey
    }
    Font {
      Color       LightGrey
      Size        10
    }
  }

  class {

    Background {
      Color CLR_BG
    }

    Border {
      Color Grey
      Thickness 1
    }

    Arrow {
      Color Grey
      Font {
        Color #bbbbbb
        Size 12
      }
    }

    Font {
      Size 12
      Color LightGrey
    }

    Stereotype {
      Font {
        Color Grey
      }
    }

  }
  
  CircledCharacter {
    Border {
      Color CLR_BG
      Thickness 1
    }
    Radius 5
    Font {
      Size 7
      Color CLR_BG
    }
  }
  
  Stereotype {
    Border {
      Color CLR_BG
      Thickness 1
    }
    C {
      Border {
        Color CLR_BG
        Thickness 1
      }
      Background {
        'Color DimGrey
      }
    }
  }
  
}

class Bdr {
}

@enduml
