@startuml

!ifndef BDR_SCN_THM
  !include thm.puml
!endif

header
2015-09-10
[[https://esf.itms.pro esf.itms.pro]]
end header

footer

© ITMS 2015-2016
end footer

title BTA UC\n

start

:bld<

split

  :be|

  split
  :nm1]
  split again
  :nm2]
  split again
  :...]
  split again
  :nmN]
  end split

  split
    :lnt-src|
    :es|
  split again
    :tpl|
  split again
    :ast|
  end split

  :lnt-pos|

split again

  :fe|

  split
    :lnt-src|
    :js|
  split again
    :lnt-src|
    :css|
  split again
    :lnt-src|
    :ng|
  split again
    :ast|
  end split
  :lnt-src|
  :bump ast|
  :html|
  :cps|
  :lnt-pos|

end split

:.tmp/bta>

:tst|

if (test result) then (success)

:dpy|
:bta>

else (fail)

  stop

endif



stop

@enduml
